"Copyright (c) 1994-2008 John Bradley Plevyak, All Rights Reserved\n"
"\n"
"The material contained in this directory is PROPRIETARY and contains\n"
"TRADE SECRETS.  You have no rights to use or view this material\n"
"in any way.  If found, please destroy at once and notify:\n"
"\n"
"John Plevyak\n"
"john@plevyak.com\n"
"3976 19th Street\n"
"San Francisco, CA, 94114\n"
"415-606-4628\n"
