OS_TYPE = $(shell uname -s | \
  awk '{ split($$1,a,"_"); printf("%s", a[1]);  }')

CFLAGS += -DUSE_GC=1 -I$(CG_ROOT) -I$(CG_ROOT)/../ifa -I$(CG_ROOT)/../plib -I/usr/local/include/gc -g -Wno-deprecated

LIBS = $(CG_ROOT)/../plib/libplib_gc.a -lm -lgc -lpcre

ifeq ($(OS_TYPE),Linux)
  LIBS += -ldl -lrt
endif

CC = g++

ifdef OPTIMIZE
  CFLAGS += -O3
endif

ifdef DEBUG
  CFLAGS += -g
endif

all: $(CG_FILES)
	@$(CC) $(CFLAGS) $(LDFLAGS) -o $(CG_TARGET) $(CG_FILES) $(LIBS)
