
OS_TYPE = $(shell uname -s | \
  awk '{ split($$1,a,"_"); printf("%s", a[1]);  }')

CFLAGS += -I$(CG_ROOT) -I/usr/local/include/gc -g -Wno-deprecated

LIBS = $(CG_ROOT)/libpyc_gc.a -lm -lgc

ifeq ($(OS_TYPE),Linux)
  LIBS += -ldl -lrt
endif

CC = g++

all: $(CG_FILES)
	@$(CC) $(CFLAGS) $(LDFLAGS) -o $(CG_TARGET) $(CG_FILES) $(LIBS)
