.TH pyc 1 "Aug 2008" PYC "Manual"
.SH NAME
.PP
pyc \- Python Compiler
.SH SYNOPSIS
.PP
.B pyc
[\fIoptions\fP]
.SH DESCRIPTION
.PP
Pyc is program for associative machine interaction.
.SH OPTIONS
.PP
.IP "-v"
Increase verbosity.
.IP "-d"
Increase debugging.
.IP "-h"
Display help.
.SH FEATURES
.PP
The features are covered in the documentation.  See the README file.
.SH FILES
.PP
None.	
.SH NO WARRANTIES
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
COPYRIGHT for more details.
.PP
Pyc Home Page: http://pyc.sourceforge.net/
.PP
The BSD General Public License.
.SH AUTHOR
.PP
John Plevyak.  Use <jplevyak at users.sourceforge.net> to contact.

