#!/bin/bash

PYTHON=python2

#VALGRIND='valgrind -q'
VALGRIND=' '

cd tests
failed=0
expected_failed=0
cp ../pyc_compat.py .
for g in *.py; do
  if [ -e "$g.ignore" ]; then continue; fi
  if [ -e "$g.flags" ]; then
    flags=$(cat "$g.flags")
  else
    flags=
  fi
  $VALGRIND ../pyc -D.. $flags "$g" >&"$g.out"
  if [ $? -ne 0 ]; then
    if [ -e "$g.expect_fail" ]; then
      echo "$g COMPILE EXPECTED FAIL"
      expected_failed=$((expected_failed + 1))
    elif [ -e "$g.check_fail" ]; then
      echo "$g COMPILE PASSED"
    else
      echo "$g ******** COMPILE FAILED ********"
      failed=$((failed + 1))
    fi
  else
    if [ -e "$g.check" ]; then
      diff "$g.out" "$g.check"
    else
      diff "$g.out" empty
    fi
    if [ $? -ne 0 ]; then
      echo "$g ******** COMPILE FAILED ********"
      failed=$((failed + 1))
    else
      echo "$g COMPILE PASSED"
      if [ -e "$g.exec.check" ]; then
        base="${g%.py}"
        $VALGRIND ./"$base" >&"$g.exec.out"
        diff "$g.exec.out" "$g.exec.check"
        if [ $? -ne 0 ]; then
          echo "$g ******** EXECUTE FAILED ********"
          failed=$((failed + 1))
        else
          echo "$g EXECUTE PASSED"
        fi
        $PYTHON "$g" >&"$g.python.out"
        diff "$g.exec.out" "$g.python.out" > /dev/null
        if [ $? -ne 0 ]; then
          if [ -e "$g.python.expect_fail" ]; then
            echo "$g PYTHON EXPECTED FAIL"
            expected_failed=$((expected_failed + 1))
          else
            echo "$g ******** CPYTHON VERIFY FAILED ********"
            diff "$g.exec.out" "$g.python.out"
            failed=$((failed + 1))
          fi
        fi
        rm -f "$base"
      fi
    fi
  fi
done
echo "---------------------------------------"
if [ "$failed" -eq 0 ]; then
  echo "ALL tests PASSED ($expected_failed expected fails)"
else
  echo "******** $failed test(s) FAILED (not including $expected_failed expected fails) *********"
fi
rm -rf ./*.o ./*.c ./*.out pyc_compat.py
cd ..
