# chr, ord, hex
print(chr(65))
print(ord('A'))
print(hex(0x5A7D))

# abs, all, any, isinstance, issubclass, str, bin, bool, int, float, bytearray
print(abs(-1))
print(all([1, 2, 3]))
print(all([1, 0, 3]))
print(any([0, 2, 0]))
print(any([0, 0, 0]))
print(isinstance("this", str))
print(isinstance("this", int))
print(isinstance("this", str))
print(issubclass(str, str))
print(issubclass(str, str))
print(issubclass(str, str))
print(str)
print(bin(-1))
print(bin(10))
print(bool(10))
print(bool(0))
print(int(3.4))
print(float(3))
x = bytearray(10)
x[1] = ord('a')
x[2] = ord('b')
print(x)
print('a' * 10)
buffer = [' '] * len("foobar")
print(buffer)

# bytearray len and str
x = bytearray(10)
x[1] = 44
print(len(x))
print(x)
