# file.seek(offset, whence) / tell() on binary and text files (rdb).
f = open("sk.bin", "wb")
f.write(b"0123456789")
print(f.tell())
f.seek(2)
f.write(b"ab")
f.close()
g = open("sk.bin", "rb")
print(g.read(3), g.tell(), g.seek(-2, 2), g.read(), g.seek(1), g.read(2), g.seek(1, 1), g.read(1))
g.close()
h = open("sk.bin")
h.seek(4)
print(h.read(), h.tell())
h.close()
